### ISSUE TITLE
About us section

### ISSUE THREAD

**Issue by Ibrahim-Jarada** [GSG-G11/tecStorm-portfolio#4]
Creating about us section and styling it

**Comment by RandSohail** [comment]
* Add images to assest file
* Structure html for About us section 
* Style css section 
* Make the design responsive  
* add hover to contact us button 
![About-us-section](https://user-images.githubusercontent.com/32583123/151068586-6639eec8-6d04-4486-a03a-c91dc1ed1319.PNG)
